links:
  link_rails: "https://www.railstutorial.org/"
  link_rails_help: "https://www.railstutorial.org/help"
  link_rails_book: "https://www.railstutorial.org/book"
  link_author: "http://www.michaelhartl.com/"
  link_rails_news: "http://news.railstutorial.org/"
