links:
  link_rails: "https://www.railstutorial.org/"
  link_rails_help: "https://www.railstutorial.org/help"
  link_rails_book: "https://www.railstutorial.org/book"
  link_author: "http://www.michaelhartl.com/"
  link_rails_news: "http://news.railstutorial.org/"
  link_gravatar: "http://gravatar.com/emails"
users_per_page: 5
posts_per_page: 3
avatar_size: 50
avatar_size_small: 30
avatar_size_show: 100
name_length: 50
email_length: 255
pass_min_length: 6
email_regex: !ruby/regexp '/\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i'
expired_time: 2
max_img_size: 5
max_content: 140
